Gearbox linear pool
joaobrunoah/balancer-v2-monorepo pull request #2
Opened 2022-11-21 01:42 UTC by joaobrunoah

# Description

Implementing Gearbox Linear Pool with Rebalancer. Gearbox team needs it to implement a boosted pool.

## Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [x] The diff is legible and has no extraneous changes
- [x] Complex code has been commented, including external interfaces
- [x] Tests are included for all code paths
- [x] The base branch is either `master`, or there's a description of how to merge

2022-11-22 04:25 UTC, rabmarut requested changes
Hey @joaobrunoah, I left a bunch of inline comments. I also notice that:
- There is no `abi` directory
- There is no `bytecode` directory
- The `build-info` directory should contain build info for the `Factory` instead of the `Pool`

2022-11-22 04:25 UTC, rabmarut commented on .gitignore
> +.idea/
In my opinion, this type of thing shouldn't be included in a project's gitignore file. The project's gitignore should only include entries that are relevant to the project itself, whereas personal or system-wide configuration stuff should go in a [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).

2022-11-22 04:25 UTC, rabmarut commented on pkg/deployments/tasks/20221116-gearbox-rebalanced-linear-pool/readme.md
> +Deployment of the `GearboxLinearPoolFactory`, for Linear Pools with a wrapped aToken. This new deployment includes a permissionless rebalancing contract that has Asset Manager privileges.
```suggestion
Deployment of the `GearboxLinearPoolFactory`, for Linear Pools with a Gearbox Diesel Token (dToken).
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/deployments/tasks/20221116-gearbox-rebalanced-linear-pool/readme.md
> +- [`GearboxLinearPoolRebalancer` ABI](./abi/GearboxLinearPoolRebalancer.json)
None of these files are included in this PR, but I think they should be.

2022-11-22 04:25 UTC, rabmarut commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +    // solhint-disable-next-line func-name-mixedcase
This was only needed for the IStaticAToken interface because of the `ASSET` and `LENDING_POOL` functions not having pretty names.
```suggestion
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +    // solhint-disable-next-line func-name-mixedcase
```suggestion
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +    ) external;
The linter prefers it on one line; only break it out if there are 3+ arguments.
```suggestion
    function removeLiquidity(uint256, address) external;
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +    function getDieselRate_RAY() external view returns (uint256);
For this one, we actually do need the hint.
```suggestion
    // solhint-disable-next-line func-name-mixedcase
    function getDieselRate_RAY() external view returns (uint256);
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPool.sol
> +        _require(address(args.mainToken) == IGearboxVault(gearboxVaultAddress).underlyingToken(), Errors.TOKENS_MISMATCH);
Line length exceeds 120 characters.
```suggestion
        _require(
            address(args.mainToken) == IGearboxVault(gearboxVaultAddress).underlyingToken(),
            Errors.TOKENS_MISMATCH
        );
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPool.sol
> +            // so we need to convert it.
Line length
```suggestion
            // This function returns a 18 decimal fixed point number, but `getDieselRate_RAY` has 27 decimals (i.e. a
            // 'ray' value) so we need to convert it.
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPool.sol
> +            // reporting invalid data to the query mechanism for swaps/joins/exits.
Line length
```suggestion
            // By maliciously reverting here, Gearbox (or any other contract in the call stack) could trick the Pool
            // into reporting invalid data to the query mechanism for swaps/joins/exits.
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPoolFactory.sol
> +        // ID, wrapped and main tokens, etc., as immutable variables.
Line length
```suggestion
        // We are going to deploy both an GearboxLinearPool and an GearboxLinearPoolRebalancer set as its Asset Manager,
        // but this creates a circular dependency problem: the Pool must know the Asset Manager's address in order to
        // call `IVault.registerTokens` with it, and the Asset Manager must know about the Pool in order to store its
        // Pool ID, wrapped and main tokens, etc., as immutable variables.
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPoolRebalancer.sol
> +    }
Private function names start with a leading underscore. (Note that this also needs to be changed everywhere it is invoked.)
```suggestion
    function _getGearboxVault(address dieselTokenAddress) private view returns (IGearboxVault) {
        address gearboxVaultAddress = IGearboxDieselToken(dieselTokenAddress).owner();
        return IGearboxVault(gearboxVaultAddress);
    }
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/solidity-utils/contracts/openzeppelin/EIP712.sol
> +    function _getChainId() private pure returns (uint256 chainId) {
Why was this modified?

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/test/GearboxLinearPool.test.ts
> +      const otherToken = await Token.create('USDC');
I would change this to DAI just to make clear that it's a different token.
```suggestion
      const otherToken = await Token.create('DAI');
```

2022-11-22 04:25 UTC, rabmarut commented on pkg/pool-linear/contracts/gearbox/GearboxLinearPoolRebalancer.sol
> +    }
If you want, there's actually another handy function in the Gearbox vault that we could use here:

`fromDiesel(uint256 amount)` converts a dToken amount to an underlying amount.

2022-11-22 13:55 UTC, joaobrunoah commented
hey @rabmarut , all comments were resolved. The only issue is: to have the bytecode, I need to deploy the contract somewhere, since it needs the contract address, right? Is there a way to get it without deploying?

2022-11-22 14:03 UTC, rabmarut commented
@joaobrunoah The bytecode is actually embedded, along with the ABI, in the build artifacts - those are the files you've put in the `abi` directory here. Typically, we trim these; we extract the `abi` component of the build artifacts and put that in the `abi` directory, while extracting the `bytecode` into a separate `bytecode` directory.

2022-11-22 15:20 UTC, joaobrunoah commented
@rabmarut Got it, fixed!

2022-11-22 17:18 UTC, rabmarut commented
@joaobrunoah I'm not sure why, but it seems like the proper format for bytecode files is to use the name `creationCode` instead of `bytecode` and to remove the `0x` from the string: https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/deployments/tasks/20221115-aave-rebalanced-linear-pool/bytecode/AaveLinearPool.json

2022-11-22 17:25 UTC, joaobrunoah commented
@rabmarut Ok, fixed!

2023-01-24 13:59 UTC, closed without merging

2023-01-24 13:59 UTC, joaobrunoah commented
Closed because Gearbox LP was created in the linear-pools new repo