Batch relayer gearbox
joaobrunoah/balancer-v2-monorepo pull request #5
Opened 2023-01-23 13:31 UTC by joaobrunoah

# Description

Including batch relayer and tests for Gearbox protocol.

## Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [x] The diff is legible and has no extraneous changes
- [x] Complex code has been commented, including external interfaces
- [x] Tests are included for all code paths
- [x] The base branch is either `master`, or there's a description of how to merge

2023-02-13 20:25 UTC, joaobrunoah commented on pkg/deployments/tasks/20230213-batch-relayer-v5/test/test.fork.ts
> +  describe.only('GearboxWrapping', async () => {
Fork tests specifically to GearboxWrapping

2023-02-17 23:01 UTC, rabmarut requested changes

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        underlying.safeApprove(address(gearboxVault), mainAmount);
I would add a comment here explaining that tokens are deposited to the Gearbox vault which is not the same as the dieselToken contract. It's a bit unintuitive since most wrapping modules operate directly on the wrappedToken.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        gearboxVault.addLiquidity(mainAmount, recipient, 0);
I would add a comment here explaining that the 0 is a referral code. It stands out to the reader that this function has an extra argument and it's being hard-coded for some reason.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        IGearboxVault gearboxVault = IGearboxVault(wrappedToken.owner());
Again, I would add a comment explaining why we are operating on another contract that is not the wrapped token.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +    address private _dieselTokenAddress;
This will always be of type `MockGearboxDieselToken`, so we should declare it that way rather than casting it every time.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +    address private immutable _underlyingToken;
This is probably more of a matter of personal preference, but since we are currently casting this to `IERC20` three times and only using the raw address once (in the `underlyingToken()` function), I would prefer to declare this as `IERC20`.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        uint256 wrappedAmount = this.toDiesel(amount);
The notation `this.function()` is used to make an external call from a contract to itself. While this is valid Solidity, it is a very rare pattern reserved only for very specific scenarios. It costs extra gas to make an external call vs simply calling functions directly.

My guess is that this is written this way because the `fromDiesel` and `toDiesel` functions are declared `external`, so it is not possible to call them directly here. There are two options to get around this:

1. Declare the functions `public`. When overriding functions from an interface (which are always `external`), it is perfectly acceptable to upgrade their access control to `public`.
2. Leave those functions `external`, but implement `private` versions (i.e., `_fromDiesel` and `_toDiesel`) which contain the function logic. Then use the `private` versions everywhere within this contract, including within the `external` versions.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        uint256 mainAmount = this.fromDiesel(wrappedAmount);
Same here re: `this.function()`.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        IERC20(_underlyingToken).safeTransferFrom(address(this), to, mainAmount);
`transferFrom` and `safeTransferFrom` are used to initiate transfers from an external source (i.e., `msg.sender`, as in a deposit). As such, they require prior approval.

For transferring our (read: the contract's) own tokens directly, we should instead use `transfer` and `safeTransfer`. These do not require approval because we are allowed to spend our own tokens however we'd like.

2023-02-17 23:01 UTC, rabmarut commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        IGearboxVault gearboxVault = IGearboxVault(wrappedToken.owner());
I would add some whitespace here as a matter of style, just to escape the prior curly brace.
```suggestion
        }
        
        IGearboxVault gearboxVault = IGearboxVault(wrappedToken.owner());
```

2023-02-17 23:01 UTC, rabmarut commented on pvt/helpers/src/test/expectEvent.ts
> +      `${expectedEvents.length} '${eventName}' events found, but no event with amount ${amount}`
I'm confused about this change. Is this an accurate reflection of what is being tested? I think we are searching for a certain number of events here, not a single event with a certain number.

2023-02-17 23:01 UTC, rabmarut commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +interface IGearboxDieselToken {
I think we should consider importing `IERC20` here and specifying that `IGearboxDieselToken` inherits `IERC20`. Then we wouldn't have to cast between the two types, and we wouldn't have to create two contract objects for the same token in our tests.

2023-02-24 17:51 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        underlying.safeApprove(address(gearboxVault), mainAmount);
Done!

2023-02-24 17:51 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        gearboxVault.addLiquidity(mainAmount, recipient, 0);
Done!

2023-02-24 17:51 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        IGearboxVault gearboxVault = IGearboxVault(wrappedToken.owner());
Done!

2023-02-24 17:51 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +    address private _dieselTokenAddress;
Done!

2023-02-24 17:52 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +    address private immutable _underlyingToken;
Done!

2023-02-24 17:52 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        uint256 wrappedAmount = this.toDiesel(amount);
Nice to know, didn't think about it before!

2023-02-24 17:52 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        uint256 mainAmount = this.fromDiesel(wrappedAmount);
Done!

2023-02-24 17:52 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/test/MockGearboxVault.sol
> +        IERC20(_underlyingToken).safeTransferFrom(address(this), to, mainAmount);
Done!

2023-02-24 17:52 UTC, joaobrunoah commented on pkg/standalone-utils/contracts/relayer/GearboxWrapping.sol
> +        IGearboxVault gearboxVault = IGearboxVault(wrappedToken.owner());
Done!

2023-02-24 17:53 UTC, joaobrunoah commented on pvt/helpers/src/test/expectEvent.ts
> +      `${expectedEvents.length} '${eventName}' events found, but no event with amount ${amount}`
My mistake, I was probably distracted with some error and changed the message in the wrong place

2023-02-24 17:54 UTC, joaobrunoah commented on pkg/interfaces/contracts/pool-linear/IGearboxDieselToken.sol
> +interface IGearboxDieselToken {
Usually IERC20 conflicts with TestToken on unit tests. It happened a lot when testing Linear Pools, but didn't happen in batch relayer tests. So, this is fixed!

2023-02-27 23:32 UTC, rabmarut approved these changes

2023-03-02 20:11 UTC, closed without merging